version: '3.1'

services:
  server:
    build: .
    container_name: test
    command: python src/main.py
#    ports:
#      - "22:22"
    env_file:
      - .env
    volumes:
      - ./results:/src/results

volumes:
  results: null