version: '3'

services:
  test:
    build: .
    container_name: test
    command: python main.py
#    ports:
#      - "22:22"
    volumes:
      - ./results:/app/src/results

volumes:
  results: null